### ISSUE TITLE
Add core Erlang functions to clojure.core

### ISSUE THREAD

**Issue by jfacorro** [clojerl/clojerl#471]
Specially the ones related to processes:

- `erlang/spawn.[1, 2, 3]`.
- `erlang/send` (will need to change the name).

**Comment by xiongtx** [comment]
Just passing through (impressive work!), but is this a good idea? `core` is already too big for its own good.

**Comment by jfacorro** [comment]
@xiongtx Honestly, I'm not sure it's a good idea, that's one of the reasons it hasn't been implemented yet.

The goal would be to have this fundamental Erlang functions available without having to `require` or `refer` the namespace all the time. It could be a different namespace (e.g. `erlang.core`?) that is referred automatically, just like `clojure.core`, when using `ns`.

Suggestions and thoughts welcome!

**Comment by jfacorro** [comment]
I agree with the points listed above by @xiongtx, thus I will close this issue. 

When there is a need to create a `erlang.core` namespace to make functions in the `erlang` module more "clojure-friendly" we can create a new issue for that.
