### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by ryukinix** [clojerl/clojerl#618]
I know that this project is work in progress, but it would be awesome a project example written in. 

EDIT: I saw the webapp hosted on clojerl organization but seems so old and this project seems so active. https://github.com/clojerl/example-web-app

**Comment by ryukinix** [comment]
Ah, I saw you have a lot of scripts of example inside of a nested directory: https://github.com/clojerl/clojerl/tree/master/scripts/examples 

A friend shared with me in https://t.me/commonlispbr

**Comment by jfacorro** [comment]
Maybe there should be a link to `scripts/examples` from the README? Would you find that useful?

What other kind of example projects would you find interesting/useful?

In general most Clojure code will compile in Clojerl, but I guess a more comprehensive guide of the implementation and the language, like Elixir has, would go a long way for helping understanding how to use Clojerl. The reason I have not invested time in this so far is because Clojerl is pretty close to Clojure in most aspects and I wanted to avoid duplicating documentation.

What do you think?

**Comment by ryukinix** [comment]
> Maybe there should be a link to scripts/examples from the README? Would you find that useful?

Yes, I think I would found more easy.

> What other kind of example projects would you find interesting/useful?

Maybe a simple API Rest? Probably using some feature of concurrency which clojure & clojerl differs.

> The reason I have not invested time in this so far is because Clojerl is pretty close to Clojure in most aspects and I wanted to avoid duplicating documentation.

I understand that. Well... I think you can still provide something minimal but functional to someone getting started to play in the local environment. I really would like this. 

> How I can do a application with this? There is something like lein to generate projects? What would be a nice template for clojerl? It's really the same as Clojure?

It would be nice see the where exists difference.

**Comment by arpunk** [comment]
> How I can do a application with this? There is something like lein to generate projects? What would be a nice template for clojerl? It's really the same as Clojure?

There is a [rebar3 template](https://github.com/clojerl/rebar3_clojerl/) for generating a basic scaffold. There is a [minor typo bug](https://github.com/clojerl/rebar3_clojerl/pull/41) but you can start running a basic app with those generators.

**Comment by jfacorro** [comment]
> It would be nice see where clojure and clojerls diffs and where it's really equal.

There is a document [here](https://clojerl.github.io/differences-with-clojure/) describing just that 😄. Let me know if there is anything missing that you wonder about but can't find there.

**Comment by jfacorro** [comment]
The README has been updated with some new information. I agree there is a lot more to be done to guide newcomers on how to get started. I have that as a pending task, but I haven't found the time to get around to it. Contributions in this and/or other aspects is very welcome! 😄
