### ISSUE TITLE
State of Clojerl?

### ISSUE THREAD

**Issue by didibus** [clojerl/clojerl#667]
Would be nice if the readme mentioned the state of Clojerl. Like what of Clojure is currently fully supported and what is still missing.

I think that could help knowing if you can adopt it for a given project or not.

Regards!

**Comment by jfacorro** [comment]
@didibus There is some documentation regarding what features from Clojure are implemented and how does it compare to it in the [clojerl.org](http://clojerl.org/) website.

If there is anything else you think I should add there or anything else you would like to know, please let me know and I can add it.

I will get back to work on Clojure on the BEAM on december, where I will implement the missing features like agents, future and promises, as well as creating documentation for how to build systems using Clojure on the BEAM.

**Comment by didibus** [comment]
Oh, it appears I had missed that link, and I didn't know there was an official we site. That does answer my question, thanks!
