### ISSUE TITLE
Create asdf installer for Clojerl

### ISSUE THREAD

**Issue by jfacorro** [clojerl/clojerl#672]
[asdf](https://asdf-vm.com/#/) is a tool to "manage multiple runtime versions with a single CLI tool". Erlang itself and other BEAM languages (e.g. Elixir) can be installed using it and it would be very nice to add Clojure on the BEAM to the mix.

Documentation to create asdf plugins [here](https://asdf-vm.com/#/plugins-create?id=whats-in-a-plugin).

Repository created [here](https://github.com/clojerl/asdf-clojerl).

**Comment by marciol** [comment]
Hi @jfacorro, I opened a PR on the [asdf-clojerl repository](https://github.com/clojerl/asdf-clojerl/pull/2)

Let me know if it's good or we need to change something.

**Comment by jfacorro** [comment]
This is awesome! I think we can merge that PR and take it from there!
