### ISSUE TITLE
Use clojerl to implement a subset of riemann.io core

### ISSUE THREAD

**Issue by joaohf** [clojerl/clojerl#696]
Hi,

Would be possible to implement riemann stream core [1] functionality using clojerl language ?

I don't expect a direct 1:1 (but most of the code, removing the java calls) code.  But I want to know if there are any critical missing feature in clojerl that block the idea. 

1: https://github.com/riemann/riemann/tree/master/src/riemann

Thanks

**Comment by jfacorro** [comment]
@joaohf I'm not familiar with Riemann or its implementation. But I skimmed through the entrypoint namespace [riemann.bin](https://github.com/riemann/riemann/blob/master/src/riemann/bin.clj) and a couple other namespaces that I think are important like `riemann.core`, `riemann.streams` and `riemann.service`.

From what I've seen in these namespaces, it doesn't look like there are any missing features that would prevent from porting it.

The following are some things that I could see at a first glance that would involve non-trivial work.

- **Dependencies**
    Riemann uses *a lot* of them, at least there are a lot listed in its [project.clj](https://github.com/riemann/riemann/blob/master/project.clj). Most of them are probably not needed for Riemann's core functionality, but some of them could be, and it would be necessary to either find an existing library in Erlang, port the Clojure dependency to Clojerl, or implement something from scratch. 
- **`java.util.concurrent`**
    The `riemann.service` namespace imports some classes from the `java.util.concurrent` package. Some of these classes perform a function that has no equivalent in the BEAM (Erlang VM), for example `ExecutorService` or `ThreadFactory`. These will need to be implemented or adapted to the tools the platform provides.
- **Refs**
    Refs are not implemented in Clojerl and there is no current plan to do include them. They are being used in `riemann.streams`, but as far as I could see, all uses are to change two values in sync (inside a `dosync`). This could be replaced with an Atom that holds a map of two keys, where the values get updated at the same time. 

In my opinion I would say it's doable, with a non-trivial amount of work. I'm curious about what you have in mind though, and why were you asking if it's possible.

Hope this helps.

**Comment by joaohf** [comment]
Thank you @jfacorro that helps. And I'll getting those points in consideration if I start something.

I've been working in a private project which uses riemann as a metric stream processor, receiving metrics from an Erlang application that collect metrics using different protocols and multiplexing it over riemann protocol. Sending the metrics to a local riemann server.

The initial idea is to get rid the JVM needed to run riemann server. As the application only uses the riemann stream processor, it would be interesting to have that engine (or most of the features) running on BEAM.

Right know I'm just exploring if the idea is feasibly or not. I guess that is but non-trivial work as you said.

**Comment by jfacorro** [comment]
@joaohf Sounds like an interesting project. I've only heard good things about Riemann.

I will close this issue for now. But please feel free to re-open it if you have any further questions or comments. 

Cheers!
