### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by mdbergmann** [clojerl/clojerl#707]
Hi.

Sorry to use the ticket management for this.

I was wondering how it works, and where to do discussions about Clojerl and the ecosystem?

Manfred

**Comment by jfacorro** [comment]
@mdbergmann There are some pointers [here](https://github.com/clojerl/clojerl#discussion), but I should add the [#clojerl](https://app.slack.com/client/T055DJ9UH/C7KBUEAMC) channel in the Erlanger slack, since that's much friendlier.

**Comment by mdbergmann** [comment]
I've seen the Clojure and Erlang mailing lists.
But I wouldn't know which I should use and then, it's not really related to both Clojure and Erlang. Well, both actually, but only slightly.
I'll check out the Slack channel. However Slack is not really suited (IMO) for doing discussions on a topic.

**Comment by jfacorro** [comment]
I'm open for suggestions 😄. What do you think is a good tool for discussions?

**Comment by mdbergmann** [comment]
I think something is not right with the Slack channel link.

Shouldn't it be a host: clojerl.slack.com or something like that?

**Comment by mdbergmann** [comment]
> What do you think is a good tool for discussions?

What about an old-school mailing list or a Google group.
There is pretty much no administration involved. Except filtering out the spam that might be there after a while.

**Comment by jfacorro** [comment]
The link should take you to erlanger.slack.com's #clojerl channel, but I just tried it by opening it in a new incognito tab, and it doesn't even include the erlanger part.

[This is the link to the Erlang slack](https://erlanger.slack.com/).
