### ISSUE TITLE
Clojerl socket REPL is behaving strangely when sending multi-lines

### ISSUE THREAD

**Issue by mauricioszabo** [clojerl/clojerl#768]
**Describe the bug**
Clojerl socket REPL is giving lots of `:function_clause` or `:badarg` when being used programatically

**To Reproduce**
Inside a Clojerl REPL, run the following command to open up a Socket REPL:

```
(do (require 'clojure.core.server)
    (clojure.core.server/start-server
     {:name "socket-repl"
      :port 4444
      :accept 'clojure.main/repl
      :address "localhost"}))
```

Create a file `input.txt`:
```
(+
1
2)
```

Then run:
```
cat input.txt | nc localhost 4444
```

**Expected behavior**
The result should be `clojure.core=> 3`

**Actual behavior**
The result is `clojure.core=> :undef`

**Context**
 - `clojerl` version Clojure 0.7.0

**Comment by mauricioszabo** [comment]
(just to be clear, last version 0.6.0 this used to work :))

**Comment by jfacorro** [comment]
Thank you for reporting this bug. 👍 

I think it might be an unintended consequence of #760. I will take a look at it.

**Comment by mauricioszabo** [comment]
@jfacorro I've just run a bisect and found this commit that breaks the Socket REPL: https://github.com/clojerl/clojerl/commit/ca889a8c23bd14e6ce8490562a04db8b85eeb804

Just tested, and seems that in the commit before it was working fine. Unfortunately, I don't know how to debug this, but will keep trying to see if I can further help :)

**Comment by mauricioszabo** [comment]
Just found the problematic line :laughing: 

```clojure
               *in* (new erlang.io.PushbackReader (InputReaderBuffer. *in* w#))
```

If I change back to:

```clojure
               *in* (new erlang.io.PushbackReader *in*)
```

Then the REPL works.

**Comment by mauricioszabo** [comment]
Ok, more info (sorry if I'm spamming you):

Just tried to debug `InputReaderBuffer`, on line 107 I've added a `prn` to identify what's wrong. And found out that `\n` is being removed from the reads.

So, if I send:

```
(+
1
2)
```

The contents of `res` will be `(+12)`, and that's what's interpreted :)

**Comment by jfacorro** [comment]
Thank you for looking into this! Great work!!! 👏 

I am on a road trip right now, but will be back on Sunday. I will take a look at the PR then.
