### ISSUE TITLE
Invalid regexp if trying to match "

### ISSUE THREAD

**Issue by mauricioszabo** [clojerl/clojerl#772]
When I try to generate a clojerl regexp to match `"`, it fails:

```clojure
clje.user=> #"foo\""
#erl[:badmatch #erl[:error #erl[#erl"\ at end of pattern" 4]]]
```

This kind of pattern works on other implementations

**Context**
 - `clojerl` version (0.7.0)

**Comment by jfacorro** [comment]
@mauricioszabo Thank you for reporting this bug! 😄. 

I think I've found the underlying issue and will open a PR soon.
