### ISSUE TITLE
Symbol resolution in Clojerl (difference from other implementations)

### ISSUE THREAD

**Issue by Zabolekar** [clojerl/clojerl#778]
Version: Clojerl 0.7.0-2031.280c117, Erlang/OTP 20
Platform: x86_64 GNU/Linux

First of all, thank you for this implementation.

I'm not sure whether the following is a bug or an intentional difference. I haven't found it in the [list of differences](https://clojerl.github.io/differences-with-clojure/).

The following works in JVM Clojure, Clojurescript, Babashka and Joker:

```
user=> (let [i 0] (defn f [] i))
#'user/f
user=> (f)
0
```

In Clojerl, however, the following happens:

```
clje.user=> (let [i 0] (defn f [] i))
#error {
 :type clojerl.Error
 :message NO_SOURCE_FILE:1:12: Unable to resolve symbol: i in this context (check usage of symbols bound outside def)}
```

Both `(let [f (let [i 0] (fn [] i))] (f))` and `(do (def i 0) (defn f [] i))` seem to behave like in other implementations.

**Comment by jfacorro** [comment]
Hi @Zabolekar!

It is as you say, this Clojure implementation behaves differently from other implementations. As the error message mentions, it is not possible to use symbols that are bound outside of a `def` expression.

```
NO_SOURCE_FILE:1:12: Unable to resolve symbol: i in this context (check usage of symbols bound outside def)
```

This is because in Clojerl each `def` is compiled to a BEAM function, which belongs to a BEAM module. BEAM functions are equivalent to top level forms in Clojure and they have to be defined at compile-time. There was no simple way I could find that would make this expression valid and keep most of the other features of Clojure equivalent.

**Comment by Zabolekar** [comment]
Thanks for the answer. So, if I understand correctly, the example where `f` is an an anonymous function bound with `let` works because it doesn't use `def`, and the example where `i` is global works because `i` is known at compile-time as well?

**Comment by Zabolekar** [comment]
Also, when using a macro, one seems to be able to bypass the restriction, but this approach is fragile for reasons I don't understand:

```
clje.user=> (defmacro make-counter [] (let [i (atom 0)] (fn [] (swap! i inc))))
#'clje.user/make-counter
clje.user=> (def a (make-counter))
#'clje.user/a
clje.user=> (a)
1
clje.user=> (a) ; verifying that the internal variable is still the same
2
clje.user=> (def b (make-counter))
#'clje.user/b
clje.user=> (b) ; verifying that the internal variable is not the same anymore
1
clje.user=> (b)
2
clje.user=> (a)
    erlang/atom_to_binary.2 (?:?)
    erlang.Fn/str.1 (/home/zabolekar/other/lisps/clojerl/src/erl/erlang/erlang.Fn.erl:26)
    clojure.core/print-simple.2 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/core_print.clje:90)
    clojure.core/pr-on.2 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/core.clje:2953)
    clojure.core/-print-sequential/6-loop_4/1-2-.4 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/core_print.clje:71)
    clojure.core/print-sequential.6 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/core_print.clje:69)
    clojure.core/pr-on.2 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/core.clje:2953)
    clojure.core/prn.1 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/core.clje:2993)
    clojure.core/println.1 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/core.clje:3011)
    clojure.main/repl-caught.2 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/main.clje:215)
    clojure.main/-repl/1-anon__56/0-2-.6 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/main.clje:302)
    clojure.main/-repl/1-loop_57/0-7-.5 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/main.clje:316)
    clojure.main/repl.1 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/main.clje:314)
    clojure.main/repl-opt.2 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/main.clje:387)
    clojure.main/main.1 (/home/zabolekar/other/lisps/clojerl/_build/default/lib/clojerl/src/clj/clojure/main.clje:461)
    clojerl_cli/run_commands.1 (/home/zabolekar/other/lisps/clojerl/src/erl/clojerl_cli.erl:104)
    clojerl_cli/start.0 (/home/zabolekar/other/lisps/clojerl/src/erl/clojerl_cli.erl:23)
    init/start_em.1 (?:?)
    init/do_boot.3 (?:?)
```

**Comment by jfacorro** [comment]
> Thanks for the answer. So, if I understand correctly, the example where `f` is an an anonymous function bound with `let` works because it doesn't use `def`, and the example where `i` is global works because `i` is known at compile-time as well?

In a nutshell, yes. There are some checks the compiler is currently doing to detect and avoid surprises for the user, it could be the case that it is trying to be too clever. 😮 😄 

> Also, when using a macro, one seems to be able to bypass the restriction, but this approach is fragile for reasons I don't understand:

This seems to be a bug, the expression `(def a (make-counter)` should fail since the value being bound to `a` is not a constant or a function. At first glance I can't tell what is happening either, I suspect there is an assumption in the code that what you did can't happen and it therefore fails when that assumption doesn't hold.

Thank you for exploring the edge cases 😄 .

**Comment by Zabolekar** [comment]
You're welcome, I *love* edge cases :)

> should fail since the value being bound to a is not a constant or a function

I'm not sure. Doesn't macro expansion happen at compile-time? Isn't the result of a macro expansion, then, known at compile-time?

By the way, when I run this example from a `.cljc` file, it works and prints 1 2 1 3, just like JVM Clojure:

```clojure
(defmacro make-counter []
  (let [i (atom 0)]
    (fn [] (swap! i inc))))

(def a (make-counter))

(println (a))
(println (a))

(def b (make-counter))

(println (b))
(println (a))
```

**Comment by jfacorro** [comment]
> I'm not sure. Doesn't macro expansion happen at compile-time? Isn't the result of a macro expansion, then, known at compile-time?

Yes, macro-expansion happens at compile-time, and as you say the result of the macro expansion is know at compile time. I haven't checked what exactly is the problem with the error generated above, but my guess is that there's a missing check in the compiler after the macro-expansion happens for an expression and using that result as the root value of a var.

For example the following expression fails to compile:

```clojure
clje.user=> (def a (let [i 1] (fn [] i)))
#error {
 :type clojerl.Error
 :message NO_SOURCE_FILE:1:1: Init value for #'clje.user/a is not a literal: #<core_eval/-create_named_fun/4-anonymous-60->}
```

Which is what I would have expected to happen with a macro that returns a `fn`, but it doesn't. The expression `(def b (f))` below should result in the same error above:

```clojure
clje.user=> (defmacro f [] (fn [] 42))
#'clje.user/f
clje.user=> (def b (f))
#'clje.user/b
clje.user=> b
#<clje.user/-f/2-anonymous-1->
```

**Comment by jfacorro** [comment]
With the change in #779 the workaround of using a macro to assign a function value is now correclty validated:

```clojure
clje.user=> (defmacro make-counter [] (let [i (atom 0)] (fn [] (swap! i inc))))
#'clje.user/make-counter
clje.user=> (def a (make-counter))
#error {
 :type clojerl.Error
 :message NO_SOURCE_FILE:1:1: Init value for #'clje.user/a is not a literal: #<clje.user/-make-counter/2-anonymous-1->}
clje.user=>
```

**Comment by Zabolekar** [comment]
Thank you for the fix :+1:
