### ISSUE TITLE
`recur` allowed in a position where other implementations don't allow it

### ISSUE THREAD

**Issue by Zabolekar** [clojerl/clojerl#786]
Version: Clojerl 0.7.0

Clojerl usually identifies tail position in the same way as other Clojure implementations do. But the following seems to work in Clojerl only:

```clojure
(defn f [i]
  (if (> i 5)
    0
    (inc (recur (inc i)))))
(f 0) ; 6
```

Why?

**Comment by jfacorro** [comment]
@Zabolekar I finally have had some time to look into this and I have found where the issue is. I will open a PR soon to fix this. Thank you for reporting this bug. 🙏

**Comment by Zabolekar** [comment]
Thank you.
