### ISSUE TITLE
Does it build on freebsd ?

### ISSUE THREAD

**Issue by devosalain** [clojerl/clojerl#843]
Does it build on freebsd ?

**Comment by arpunk** [comment]
Yes, given you have Erlang/OTP and rebar3.

**Comment by 3xtraterrestrial** [comment]
I am having current issues with building in ( FreeBSD 14.0-RELEASE-p8 amd64 ) when git cloning and moving into directory to run make I will get the following errors. 

line 11: Unknown modifier "format(erlang"
line 11: Unknown modifier "system_info(otp_release"

Currently have following packages from Freebsd >>> 
Erlang = 25.3.2.12_1,4
Rebar3 = 3.23.0,1

**Comment by jfacorro** [comment]
I am closing this issue in favor of #844

**Comment by jfacorro** [comment]
I am closing this issue in favor of https://github.com/clojerl/clojerl/issues/844

**Comment by jfacorro** [comment]
I am closing this issue in favor of https://github.com/clojerl/clojerl/issues/844
